apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ktailor-selfsigned
  namespace: ktailor
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ktailor-serving-cert
  namespace: ktailor
spec:
  dnsNames:
  - ktailor.ktailor.svc
  - ktailor.ktailor.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: ktailor-selfsigned
  secretName: ktailor-webhook-certs
