#
# Marty McFly app for demonstrating timetravel for containers
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marty-mcfly
  namespace: default
  labels:
    app: marty
    ktailor.dev/fit: "local.timetravel-template-1985"

spec:
  selector:
    matchLabels:
      app: marty
  replicas: 1

  template:
    metadata:
      labels:
        app: marty
    spec:
      containers:
        - name:  marty
          image: katalytic/martymcfly:latest
          ports:
            - containerPort: 8080

---
# service
apiVersion: v1
kind: Service
metadata:
  name: marty

# deploy with NodePort, access with nginx by proxypass to localhost:30000
spec:
  type: NodePort
  selector:
    app: marty
  ports:
    - name: http
      nodePort: 30000
      port: 80
      targetPort: 8080
